version: '1.0.0.{build}'
image: Visual Studio 2019
configuration:
  - Debug
  - Release
build_script:
  - echo "Building for %CONFIGURATION%"
  - dotnet --list-sdks
  - dotnet restore
  - dotnet build -c %CONFIGURATION%
test_script:
  - ps: dotnet test .\test\DotNetEnv.Tests\DotNetEnv.Tests.csproj
  - ps: if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
cache:
  - '%USERPROFILE%\.nuget\packages'
